name: 'NPM Custom Action'
description: 'Installing and Caching NPM packages'
inputs:
  path-of-folder:
    description: 'The path of Folder'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: ${{inputs.path-of-folder}}
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
    # each command of run in the composite action requires a shell
    - name: Install dependencies
      run: npm install
      shell: bash