name: Solar system

on:
  workflow_call:
    inputs:
      mongodb-uri:
        required: true
        type: string
      environment:
        required: true
        type: string
      kubectl_ver:
        required: false
        type: string
        default: v1.27.0
      k8s_dir:
        description: Environment
        required: true
        type: string
        default: kubernetes/
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true


jobs:
  redeploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ steps.save_ingress_ip.outputs.INGRESS_IP }}"
    outputs:
      APP_INGRESS_URL: "https://${{ steps.save_ingress_ip.outputs.INGRESS_IP }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: ${{ inputs.kubectl_ver }}
        id: install

      - name: Setup kubecontext
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.k8s-kubeconfig }}'

      - name: Check kubectl
        run: kubectl version -o yaml
        continue-on-error: true

      - name: Save INGRESS_IP
        run: >
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services
          ingress-nginx-controller -o
          jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Create mongodb secret
        run: echo Create secret ${{ secrets.mongodb-password }} for ${{ inputs.mongodb-uri }}
      
      - name: Replace kubernetes files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{ inputs.k8s_dir }}/${{ inputs.environment }}/*.yaml"]'
        env:
          NAMESPACE: '${{ vars.NAMESPACE }}'
          REPLICAS: '${{ vars.REPLICAS }}'
          IMAGE: >-
            ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha
            }}
          INGRESS_IP: '${{ env.INGRESS_IP }}'

      - name: Check yaml manifest
        run: cat kubernetes/development/*.yaml

      - name: Deploy to dev
        run: echo kubectl apply -f kubernetes/development
            