on:
    pull_request:
        types:
          - opened

jobs:
    testing-action:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Checkout Repositoty
              uses: actions/checkout@v4
            
            - name: Post PR Comment 
              uses: kaiscerev1/Docker-Custom-Action@main
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                giphy-api-key: ${{ secrets.GIPHY_API_KEY }}